[package]
name = "ffi"
version = "0.1.0"
authors = ["Aki <wuminzhe@gmail.com>"]
edition = "2018"
include = [
    "go.mod",
    "go.sum",
    "build.rs",
    "pkg/**/*",
    "src/**/*",
    "Cargo.toml",
]
links = "darwinia-shadow"

[dependencies]
libc = "0.2.71"